from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone, date
from zoneinfo import ZoneInfo
from sqlalchemy import text
from .db import SessionLocal


def _dt(raw: str) -> datetime:
    d=datetime.fromisoformat(str(raw).replace('Z','+00:00'))
    if d.tzinfo is None:
        d=d.replace(tzinfo=timezone.utc)
    return d


def get_appointment_settings(site_id: str) -> dict|None:
    with SessionLocal() as db:
        row=db.execute(text('SELECT * FROM appointment_settings WHERE site_id=:s'),{'s':site_id}).mappings().first()
    return dict(row) if row else None


def _zone(settings: dict) -> ZoneInfo:
    try:
        return ZoneInfo(str(settings.get('timezone') or 'UTC'))
    except Exception:
        return ZoneInfo('UTC')


def _weekdays(settings: dict) -> set[int]:
    try:
        raw=json.loads(settings.get('weekdays_json') or '[]')
        return {int(x) for x in raw if 0 <= int(x) <= 6}
    except Exception:
        return {0,1,2,3,4}


def _occupied(site_id: str, start_utc: datetime, end_utc: datetime) -> list[datetime]:
    with SessionLocal() as db:
        rows=db.execute(text("SELECT starts_at FROM appointments WHERE site_id=:s AND status='BOOKED'"),{'s':site_id}).all()
    values=[]
    for row in rows:
        try:
            d=_dt(row[0]).astimezone(timezone.utc)
        except Exception:
            continue
        if start_utc - timedelta(days=1) <= d <= end_utc + timedelta(days=1):
            values.append(d)
    return values


def slot_is_available(site_id: str, starts_at: str, *, require_settings: bool=False) -> tuple[bool,str|None]:
    settings=get_appointment_settings(site_id)
    if not settings:
        return (False,'Appointments are not configured') if require_settings else (True,None)
    try:
        start=_dt(starts_at)
    except Exception:
        return False,'Invalid appointment time'
    if start < datetime.now(timezone.utc)+timedelta(minutes=5):
        return False,'Appointment must be at least 5 minutes in the future'
    zone=_zone(settings); local=start.astimezone(zone)
    if local.weekday() not in _weekdays(settings):
        return False,'The business is not accepting appointments on that day'
    start_hour=int(settings.get('start_hour') or 9); end_hour=int(settings.get('end_hour') or 17)
    duration=max(5,int(settings.get('duration_minutes') or 60)); buffer=max(0,int(settings.get('buffer_minutes') or 0))
    opening=local.replace(hour=start_hour,minute=0,second=0,microsecond=0)
    closing=local.replace(hour=end_hour,minute=0,second=0,microsecond=0)
    if local < opening or local+timedelta(minutes=duration) > closing:
        return False,'That time is outside the configured appointment hours'
    # Only accept canonical slot boundaries generated by this engine.
    step=duration+buffer
    offset=int((local-opening).total_seconds()//60)
    if offset < 0 or offset % step != 0:
        return False,'That time is not an available appointment slot'
    target=start.astimezone(timezone.utc)
    for other in _occupied(site_id,target-timedelta(hours=24),target+timedelta(hours=24)):
        # Buffer applies before and after occupied bookings.
        if abs((target-other).total_seconds()) < (duration+buffer)*60:
            return False,'That appointment slot is no longer available'
    return True,None


def available_slots(site_id: str, *, requested_date: str|None=None, daypart: str|None=None, days_ahead: int=14, limit: int=8) -> list[str]:
    settings=get_appointment_settings(site_id)
    if not settings:
        return []
    zone=_zone(settings); now=datetime.now(timezone.utc).astimezone(zone)
    start_hour=int(settings.get('start_hour') or 9); end_hour=int(settings.get('end_hour') or 17)
    duration=max(5,int(settings.get('duration_minutes') or 60)); buffer=max(0,int(settings.get('buffer_minutes') or 0)); step=duration+buffer
    weekdays=_weekdays(settings)
    wanted_date=None
    if requested_date:
        try: wanted_date=date.fromisoformat(requested_date)
        except Exception: wanted_date=None
    out=[]
    max_days=max(1,min(int(days_ahead),60))
    for add in range(max_days+1):
        d=(now+timedelta(days=add)).date()
        if wanted_date and d!=wanted_date: continue
        if d.weekday() not in weekdays: continue
        cur=datetime(d.year,d.month,d.day,start_hour,0,tzinfo=zone)
        end=datetime(d.year,d.month,d.day,end_hour,0,tzinfo=zone)
        while cur+timedelta(minutes=duration) <= end:
            if cur > now+timedelta(minutes=5):
                if daypart:
                    h=cur.hour; dp=daypart.lower()
                    if dp=='morning' and h>=12: cur+=timedelta(minutes=step); continue
                    if dp=='afternoon' and not (12<=h<17): cur+=timedelta(minutes=step); continue
                    if dp in {'evening','night'} and h<17: cur+=timedelta(minutes=step); continue
                iso=cur.astimezone(timezone.utc).isoformat()
                ok,_=slot_is_available(site_id,iso,require_settings=True)
                if ok:
                    out.append(iso)
                    if len(out)>=max(1,min(int(limit),20)): return out
            cur+=timedelta(minutes=step)
        if wanted_date and d==wanted_date: break
    return out
