import React, {useEffect, useReducer, useRef} from 'react';
import {StudioContext, studioReducer, initialState} from './store';
import {CanvasNode} from './components/CanvasNode';
import {ContextToolbar} from './components/ContextToolbar';
import {CMSPanel} from './components/CMSPanel';
import {AddPanel} from './components/AddPanel';
import {AssetsPanel} from './components/AssetsPanel';
import {SiteStylesPanel} from './components/SiteStylesPanel';
import {PageNavigator} from './components/PageNavigator';
import {PagesPanel} from './components/PagesPanel';
import {fitCanvasZoom,screenToCanvas} from './engine';

type Rail = 'templates' | 'elements' | 'text' | 'brand' | 'uploads' | 'tools' | 'projects' | 'apps' | 'photos';
const rails: Array<[Rail, string]> = [
  ['templates', 'Templates'], ['elements', 'Elements'], ['text', 'Text'], ['brand', 'Brand'],
  ['uploads', 'Uploads'], ['tools', 'Tools'], ['projects', 'Projects'], ['apps', 'Apps'], ['photos', 'Photos'],
];
const RailIcon=({id}:{id:Rail})=>{
  const paths:Record<Rail,React.ReactNode>={
    templates:<><rect x="5" y="4" width="14" height="16" rx="2"/><path d="M9 4v16"/></>,
    elements:<><path d="M11 5.5C11 3.6 9.5 2 7.5 2S4 3.6 4 5.5 5.5 9 7.5 9H11V5.5ZM13 5.5C13 3.6 14.5 2 16.5 2S20 3.6 20 5.5 18.5 9 16.5 9H13V5.5ZM11 11H7.5C5.5 11 4 12.5 4 14.5S5.5 18 7.5 18 11 16.5 11 14.5V11ZM13 11h3.5c2 0 3.5 1.5 3.5 3.5S18.5 18 16.5 18 13 16.5 13 14.5V11Z"/></>,
    text:<><path d="M5 5h14M12 5v14M8 19h8"/></>,
    brand:<><path d="M5 9.5h14v9H5zM8 9.5V7.8A2.8 2.8 0 0 1 10.8 5h2.4A2.8 2.8 0 0 1 16 7.8v1.7"/><path d="M8.2 14c1.1-2 2.6-2 3.8 0 1.2 2 2.7 2 3.8 0"/></>,
    uploads:<><path d="M7 17.5h10a4 4 0 0 0 .9-7.9A6 6 0 0 0 6.3 9 4.5 4.5 0 0 0 7 17.5Z"/><path d="M12 16V9M9 12l3-3 3 3"/></>,
    tools:<><path d="M5 17.5 14.5 8M13.5 5.5l5 5M4 20l4.2-1.1-3.1-3.1L4 20Z"/><path d="m16.8 3 .5 1.4 1.4.5-1.4.5-.5 1.4-.5-1.4-1.4-.5 1.4-.5.5-1.4Z"/></>,
    projects:<><path d="M4 7h6l2 2h8v10H4V7Z"/></>,
    apps:<><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><path d="M17 14v6M14 17h6"/></>,
    photos:<><rect x="4" y="5" width="16" height="14" rx="2"/><circle cx="9" cy="10" r="1.5"/><path d="m6 17 4-4 3 3 2-2 3 3"/></>,
  };
  return <svg className={`rail-icon rail-icon-${id}`} viewBox="0 0 24 24" aria-hidden="true" focusable="false">{paths[id]}</svg>;
};
const UtilityIcon=({name}:{name:'pencil'|'cloud'|'analytics'|'messages'})=>{const paths={pencil:<><path d="m4 20 4.2-1 10.6-10.6-3.2-3.2L5 15.8 4 20Z"/><path d="m13.8 7 3.2 3.2"/></>,cloud:<><path d="M7.5 18h9a4 4 0 0 0 .8-7.9A5.7 5.7 0 0 0 6.4 9.4 4.3 4.3 0 0 0 7.5 18Z"/><path d="m9.5 14 2 2 4-4"/></>,analytics:<><path d="M5 19V9M12 19V5M19 19v-7M3 21h18"/></>,messages:<><path d="M20 14a4 4 0 0 1-4 4H9l-5 3 1.5-4A7.5 7.5 0 0 1 4 12c0-4 3.6-7 8-7s8 3 8 7v2Z"/></>};return <svg className="utility-icon" viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>};
const acceptsChildren = (type: string) => ['page', 'section', 'container', 'stack', 'flex', 'grid', 'repeater', 'list', 'gallery'].includes(type);

export function App() {
  const [state, dispatch] = useReducer(studioReducer, initialState);
  const [rail, setRail] = React.useState<Rail>('templates');
  const [saveStatus, setSaveStatus] = React.useState<'Saved' | 'Unsaved changes' | 'Saving…' | 'Save failed' | 'Conflict detected' | 'Offline'>('Saved');
  const [preview, setPreview] = React.useState(false), [leftOpen, setLeftOpen] = React.useState(false), [context, setContext] = React.useState<{x:number;y:number}|null>(null), [toast, setToast] = React.useState(''), [fileDrop, setFileDrop] = React.useState(false);
  const timer = useRef<ReturnType<typeof setTimeout>|null>(null), saving = useRef(false), pending = useRef<any>(null), skipRevision = useRef<number|null>(null);
  const pan = useRef<{x:number;y:number;left:number;top:number}|null>(null);
  const siteId = (window as any).ZYLORA_STUDIO_CONTEXT?.siteId, csrf = (window as any).ZYLORA_STUDIO_CONTEXT?.csrfToken, project = (window as any).ZYLORA_STUDIO_CONTEXT?.siteName || 'Untitled website';

  useEffect(() => { if (!siteId) return; fetch(`/api/sites/${siteId}/studio-migrate`, {method:'POST', headers:{'X-CSRF-Token':csrf}}).then(async r => { const d=await r.json(); if(!r.ok) throw new Error(d?.detail?.message||'Studio could not be loaded'); return d; }).then(d => d.document && dispatch({type:'SET_DOCUMENT',payload:d.document})).catch(() => setSaveStatus(navigator.onLine?'Save failed':'Offline')); }, [siteId,csrf]);
  useEffect(() => { const online=()=>setSaveStatus(s=>s==='Offline'?'Unsaved changes':s), offline=()=>setSaveStatus('Offline'); addEventListener('online',online); addEventListener('offline',offline); return()=>{removeEventListener('online',online);removeEventListener('offline',offline)}; }, []);
  useEffect(() => {
    if(!state.document || state.historyIndex<=0)return;
    if(skipRevision.current===state.document.revision){skipRevision.current=null;return}
    setSaveStatus(navigator.onLine?'Unsaved changes':'Offline'); if(timer.current)clearTimeout(timer.current);
    const save=(document:any)=>{ if(!navigator.onLine){pending.current=document;setSaveStatus('Offline');return} if(saving.current){pending.current=document;return} saving.current=true;setSaveStatus('Saving…'); const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000); fetch(`/api/sites/${siteId}/studio-save`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(document),signal:controller.signal}).then(async r=>({ok:r.ok,status:r.status,data:await r.json()})).then(({ok,status,data})=>{clearTimeout(timeout);saving.current=false;if(ok&&data.ok){skipRevision.current=data.newRevision;dispatch({type:'SYNC_REVISION',payload:data.newRevision});const next=pending.current;pending.current=null;if(next)save({...next,revision:data.newRevision});else setSaveStatus('Saved')}else setSaveStatus(status===409?'Conflict detected':'Save failed')}).catch(()=>{clearTimeout(timeout);saving.current=false;pending.current=document;setSaveStatus(navigator.onLine?'Save failed':'Offline')})};
    timer.current=setTimeout(()=>save(state.document),700); return()=>{if(timer.current)clearTimeout(timer.current)};
  }, [state.document,siteId,csrf]);
  useEffect(() => { const key=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(e.code==='Space'&&!target?.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(target?.tagName)){(window as any).__zyloraSpacePressed=true;if(e.type==='keydown')e.preventDefault()}if(target?.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(target?.tagName))return;const mod=e.ctrlKey||e.metaKey;if((e.key==='Delete'||e.key==='Backspace')&&state.selectedNodeIds.length){e.preventDefault();dispatch({type:'DELETE_SELECTED'})}else if(mod&&e.key.toLowerCase()==='c'){e.preventDefault();dispatch({type:'COPY_SELECTED'})}else if(mod&&e.key.toLowerCase()==='x'){e.preventDefault();dispatch({type:'CUT_SELECTED'})}else if(mod&&e.key.toLowerCase()==='v'){e.preventDefault();dispatch({type:'PASTE'})}else if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();dispatch({type:'DUPLICATE_SELECTED'})}else if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();dispatch({type:e.shiftKey?'REDO':'UNDO'})}else if(mod&&(e.key==='='||e.key==='+')){e.preventDefault();dispatch({type:'SET_ZOOM',payload:state.zoom+.1})}else if(mod&&e.key==='-'){e.preventDefault();dispatch({type:'SET_ZOOM',payload:state.zoom-.1})}else if(state.selectedNodeIds.length&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?10:1;dispatch({type:'NUDGE_SELECTED',payload:{x:e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,y:e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0}})}else if(e.key==='Escape'){dispatch({type:'SET_CROP_MODE',payload:null});dispatch({type:'SELECT_NODE',payload:[]});setContext(null)}};const up=(e:KeyboardEvent)=>{if(e.code==='Space')(window as any).__zyloraSpacePressed=false};addEventListener('keydown',key);addEventListener('keyup',up);return()=>{removeEventListener('keydown',key);removeEventListener('keyup',up)}},[state.selectedNodeIds,state.zoom]);

  const page=state.document?.pages[state.currentPageId], width=state.currentBreakpoint==='desktop'?1360:state.currentBreakpoint==='tablet'?768:390;
  const fit=()=>{const area=document.querySelector('.canvas-workspace')?.getBoundingClientRect();if(area)dispatch({type:'SET_ZOOM',payload:fitCanvasZoom(area.width,width)})};
  const publish=async()=>{setToast('Publishing your site…');const r=await fetch(`/api/sites/${siteId}/publish`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:'{}'});const d=await r.json();setToast(r.ok?'Published':'Publish failed: '+(d?.detail?.message||d?.detail||'unknown error'))};
  const insertNode=(label:string,type:string,parentId?:string,node?:any,point?:{x:number;y:number})=>{const visual=!['section','page','navigation','footer'].includes(type),base=node||{type,metadata:{displayName:label}},css={...(base.style?.css||{}),...(visual&&point?{position:'absolute',left:`${Math.round(Math.max(0,point.x))}px`,top:`${Math.round(Math.max(0,point.y))}px`}:{})};dispatch({type:'INSERT_NODE',payload:{parentId,node:{...base,type,metadata:{displayName:label,...(base.metadata||{})},style:{css,tokens:{...(base.style?.tokens||{})}}}}})};
  const uploadDropped=async(file:File,clientX:number,clientY:number)=>{const body=new FormData();body.append('file',file);setToast('Uploading '+file.name+'…');const r=await fetch(`/api/sites/${siteId}/assets`,{method:'POST',headers:{'X-CSRF-Token':csrf},body});const d=await r.json();if(!r.ok||!d.asset){setToast('Upload failed');return}const canvas=document.querySelector('.studio-canvas')?.getBoundingClientRect();const point=canvas?screenToCanvas({x:clientX,y:clientY},canvas,{zoom:state.zoom}):{x:160,y:110};dispatch({type:'INSERT_NODE',payload:{node:{type:'image',content:{src:d.asset.url,asset_id:d.asset.id,alt:d.asset.alt_text||''},style:{css:{width:'320px',height:'220px',objectFit:'cover',position:'absolute',left:`${Math.round(Math.max(0,point.x-160))}px`,top:`${Math.round(Math.max(0,point.y-110))}px`},tokens:{}},metadata:{displayName:'Image frame',kind:'image-frame'}}}});setToast('Image added to canvas')};
  const panel=rail==='templates'?<AddPanel mode="sections"/>:rail==='elements'?<AddPanel mode="elements"/>:rail==='text'?<AddPanel mode="text"/>:rail==='brand'?<SiteStylesPanel/>:rail==='uploads'||rail==='photos'?<AssetsPanel/>:rail==='tools'?<AddPanel mode="sections"/>:rail==='projects'?<PagesPanel/>:<><AddPanel mode="apps"/><CMSPanel/></>;
  const chooseRail=(id:Rail)=>{if(rail===id)setLeftOpen(v=>!v);else{setRail(id);setLeftOpen(true)}};
  const onWorkspaceDrop=(e:React.DragEvent)=>{e.preventDefault();setFileDrop(false);const file=e.dataTransfer.files?.[0];if(file){if(file.type.startsWith('image/'))uploadDropped(file,e.clientX,e.clientY);else setToast('Only image files can be added to the canvas');return}const raw=e.dataTransfer.getData('application/x-zylora-node')||((window as any).__zyloraDraggingNode?JSON.stringify((window as any).__zyloraDraggingNode):'');if(raw){try{const data=JSON.parse(raw),target=(e.target as HTMLElement).closest<HTMLElement>('[data-studio-id]'),targetNode=target&&state.document?.pages[state.currentPageId]?.nodes[target.dataset.studioId||''],parentId=targetNode&&acceptsChildren(target.dataset.studioType||'')?target?.dataset.studioId:undefined,canvas=document.querySelector('.studio-canvas')?.getBoundingClientRect(),point=canvas?screenToCanvas({x:e.clientX,y:e.clientY},canvas,{zoom:state.zoom}):undefined;insertNode(data.label||'Text',data.type||'text',parentId,data.node,point&&{x:point.x-60,y:point.y-20})}catch{setToast('That item could not be added')}}};

  return <StudioContext.Provider value={{state,dispatch}}><div className={`zylora-studio-app${leftOpen?' panel-open':''}`} onClick={()=>context&&setContext(null)}>
    <header className="studio-topbar"><div className="topbar-left"><button onClick={()=>{setRail('templates');setLeftOpen(true)}}>File</button><button onClick={()=>dispatch({type:'SET_BREAKPOINT',payload:state.currentBreakpoint==='desktop'?'tablet':state.currentBreakpoint==='tablet'?'mobile':'desktop'})}>Resize</button><button className="editing-menu" onClick={()=>setPreview(false)} aria-label="Editing mode"><UtilityIcon name="pencil"/>Editing⌄</button><span className="top-divider"/><span className={`cloud-save ${saveStatus.toLowerCase().replace(/\W/g,'-')}`} title={saveStatus} aria-label={saveStatus}><UtilityIcon name="cloud"/></span></div><div className="topbar-center"><b>{project}</b><span> - Website</span></div><div className="topbar-right"><a className="trial-link" href="/choose-plan"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 8 4 3 4-6 4 6 4-3-2 10H6L4 8Z"/></svg>Start your free trial</a><a className="top-icon account-icon" href="/dashboard/settings" aria-label="Account"><span/></a><a className="top-icon" href="/dashboard/analytics" aria-label="Analytics"><UtilityIcon name="analytics"/></a><a className="top-icon" href="/dashboard/leads" aria-label="Messages"><UtilityIcon name="messages"/></a><button onClick={()=>setPreview(!preview)}>{preview?'Edit':'Preview'}</button><button className="primary" onClick={publish}>Publish website</button><button className="share-button" onClick={()=>navigator.clipboard?.writeText(location.href).then(()=>setToast('Editor link copied'))}>Share</button></div></header>
    <div className="studio-main"><nav className="tool-rail" aria-label="Studio tools">{rails.map(([id,label])=><button key={id} className={rail===id&&leftOpen?'active':''} onClick={()=>chooseRail(id)} title={label} aria-label={label}><RailIcon id={id}/><span>{label}</span></button>)}</nav>{leftOpen&&<aside className="studio-sidebar-left">{panel}<button className="panel-collapse" onClick={()=>setLeftOpen(false)} aria-label="Close tool panel">‹</button></aside>}
      <main className={`canvas-workspace ${preview?'preview-mode':''}`} onClick={e=>{if(e.target===e.currentTarget)dispatch({type:'SELECT_NODE',payload:[]})}} onWheel={e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();dispatch({type:'SET_ZOOM',payload:state.zoom+(e.deltaY>0?-.05:.05)})}}} onPointerDown={e=>{if(e.button===1||(e.button===0&&(window as any).__zyloraSpacePressed)){e.preventDefault();const el=e.currentTarget as HTMLElement;pan.current={x:e.clientX,y:e.clientY,left:el.scrollLeft,top:el.scrollTop};el.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{if(pan.current){e.preventDefault();const el=e.currentTarget as HTMLElement;el.scrollLeft=pan.current.left-(e.clientX-pan.current.x);el.scrollTop=pan.current.top-(e.clientY-pan.current.y)}}} onPointerUp={e=>{if(pan.current){const el=e.currentTarget as HTMLElement;el.releasePointerCapture?.(e.pointerId)}pan.current=null}} onPointerCancel={()=>{pan.current=null}} onContextMenu={e=>{if(state.selectedNodeIds.length){e.preventDefault();setContext({x:e.clientX,y:e.clientY})}}} onDragEnter={e=>{if(Array.from(e.dataTransfer.types).some(t=>t==='Files'||t==='application/x-zylora-node')){e.preventDefault();setFileDrop(true)}}} onDragOver={e=>{if(Array.from(e.dataTransfer.types).some(t=>t==='Files'||t==='application/x-zylora-node'))e.preventDefault()}} onDragLeave={e=>{if(e.currentTarget===e.target)setFileDrop(false)}} onDrop={onWorkspaceDrop}>
        {!!state.selectedNodeIds.length&&<div className="canvas-toolbar-dock"><ContextToolbar onFit={fit} onPreview={()=>setPreview(!preview)}/><span className="device-toolbar">{(['desktop','tablet','mobile'] as const).map(bp=><button key={bp} className={state.currentBreakpoint===bp?'active':''} title={bp} aria-label={`${bp} preview`} onClick={()=>dispatch({type:'SET_BREAKPOINT',payload:bp})}>{bp==='desktop'?'▰':'▯'}</button>)}</span></div>}{fileDrop&&<div className="canvas-file-drop" aria-live="polite">Drop to add to your page</div>}<div className="artboard-wrap" style={{width:width*state.zoom}}><div className="studio-canvas" style={{width,height:'auto',minHeight:766,transform:`scale(${state.zoom})`}}>{page?<CanvasNode nodeId={page.rootNodeId}/>:<div className="canvas-loading"><span/><p>Preparing your canvas…</p></div>}</div></div>{state.snapLines.map((line,i)=><div key={i} className={`snap-guide ${line.orientation}`} style={line.orientation==='vertical'?{left:line.position*state.zoom}:{top:line.position*state.zoom}}/>)}<PageNavigator onFit={fit}/></main>
    </div><nav className="studio-mobile-nav" aria-label="Mobile Studio tools">{rails.map(([id,label])=><button key={id} className={rail===id&&leftOpen?'active':''} onClick={()=>chooseRail(id)} title={label} aria-label={label}><RailIcon id={id}/><span>{label}</span></button>)}</nav>
    {context&&<div className="context-menu" style={{left:context.x,top:context.y}} role="menu"><button onClick={()=>dispatch({type:'CUT_SELECTED'})}>Cut <kbd>Ctrl X</kbd></button><button onClick={()=>dispatch({type:'COPY_SELECTED'})}>Copy <kbd>Ctrl C</kbd></button><button onClick={()=>dispatch({type:'PASTE'})} disabled={!state.clipboard}>Paste <kbd>Ctrl V</kbd></button><hr/><button onClick={()=>dispatch({type:'DUPLICATE_SELECTED'})}>Duplicate <kbd>Ctrl D</kbd></button><button onClick={()=>dispatch({type:'DELETE_SELECTED'})}>Delete <kbd>Del</kbd></button><button onClick={()=>dispatch({type:'GROUP_SELECTED'})} disabled={state.selectedNodeIds.length<2}>Group</button><button onClick={()=>dispatch({type:'UNGROUP_SELECTED'})} disabled={state.selectedNodeIds.length!==1}>Ungroup</button><hr/><button onClick={()=>state.selectedNodeIds[0]&&dispatch({type:'REORDER_NODE',payload:{nodeId:state.selectedNodeIds[0],direction:'front'}})}>Bring forward</button><button onClick={()=>state.selectedNodeIds[0]&&dispatch({type:'REORDER_NODE',payload:{nodeId:state.selectedNodeIds[0],direction:'back'}})}>Send backward</button></div>}{toast&&<div className="studio-toast" role="status"><span>{toast}</span><button onClick={()=>setToast('')}>×</button></div>}
  </div></StudioContext.Provider>;
}
