
'use client';
import {FormEvent,useEffect,useState} from 'react';
import {api} from '../lib/api';
import TemplateAdmin from './TemplateAdmin';
type Lead={id:number;lead_code:string;name:string;website_type:string;status:string};
type SessionUser={id:number;email:string;role:string;plan:string};
type Post={id:number;title:string;slug:string;excerpt:string;content:string;featured_image?:string|null;seo_title?:string|null;seo_description?:string|null;canonical_url?:string|null;status:string;publish_at?:string|null};
const emptyPost={title:'',slug:'',excerpt:'',content:'',featured_image:'',seo_title:'',seo_description:'',canonical_url:''};
export default function AdminClient(){
 const[config,setConfig]=useState<Record<string,string>>({}),[draft,setDraft]=useState<Record<string,string>>({});
 const[leads,setLeads]=useState<Lead[]>([]),[posts,setPosts]=useState<Post[]>([]),[post,setPost]=useState<any>(emptyPost),[editing,setEditing]=useState<number|null>(null);
 const[msg,setMsg]=useState(''),[authorized,setAuthorized]=useState(false);
 const[audience,setAudience]=useState('USERS'),[mailSubject,setMailSubject]=useState(''),[mailHtml,setMailHtml]=useState('');
 useEffect(()=>{(async()=>{try{const me=await api<SessionUser>('/auth/me');if(me.role!=='SUPER_ADMIN'){location.replace('/dashboard');return;}const[c,l,b]=await Promise.all([api<Record<string,string>>('/admin/config'),api<Lead[]>('/managed/enquiries'),api<Post[]>('/blog')]);setConfig(c);setDraft(c);setLeads(l);setPosts(b);setAuthorized(true)}catch(e:any){if(e.status===401||e.status===403)location.replace('/dashboard');else setMsg(e.message)}})()},[]);
 async function update(key:string){const value=draft[key]??'',previous=config[key]??'';try{await api(`/admin/config/${encodeURIComponent(key)}`,{method:'PUT',body:JSON.stringify({value})});setConfig(c=>({...c,[key]:value}));setMsg('Configuration saved.')}catch(e:any){setDraft(d=>({...d,[key]:previous}));setMsg(`Save failed: ${e.message}`)}}
 async function leadStatus(id:number,status:string){try{const l=await api<Lead>(`/managed/enquiries/${id}`,{method:'PATCH',body:JSON.stringify({status})});setLeads(xs=>xs.map(x=>x.id===id?l:x))}catch(e:any){setMsg(e.message)}}
 function editPost(p:Post){setEditing(p.id);setPost({...p,featured_image:p.featured_image||'',seo_title:p.seo_title||'',seo_description:p.seo_description||'',canonical_url:p.canonical_url||''});document.getElementById('blog-editor')?.scrollIntoView({behavior:'smooth'})}
 async function savePost(e:FormEvent){e.preventDefault();try{const payload={...post};const saved=editing?await api<Post>(`/blog/${editing}`,{method:'PATCH',body:JSON.stringify(payload)}):await api<Post>('/blog',{method:'POST',body:JSON.stringify(payload)});setPosts(xs=>editing?xs.map(x=>x.id===editing?saved:x):[saved,...xs]);setEditing(saved.id);setPost(saved);setMsg('Blog post saved.')}catch(e:any){setMsg(e.message)}}
 async function setPostStatus(id:number,status:string,publish_at?:string|null){try{const saved=await api<Post>(`/blog/${id}/status`,{method:'PATCH',body:JSON.stringify({status,publish_at:publish_at||null})});setPosts(xs=>xs.map(x=>x.id===id?saved:x));if(editing===id)setPost(saved)}catch(e:any){setMsg(e.message)}}
 async function removePost(id:number){if(!confirm('Delete this blog post permanently?'))return;try{await api(`/blog/${id}`,{method:'DELETE'});setPosts(xs=>xs.filter(x=>x.id!==id));if(editing===id){setEditing(null);setPost(emptyPost)}setMsg('Blog post deleted.')}catch(e:any){setMsg(e.message)}}
 async function sendBulk(e:FormEvent){e.preventDefault();if(!confirm(`Send this email to ${audience.toLowerCase().replace('_',' ')}?`))return;try{const r=await api<any>('/admin/email/bulk',{method:'POST',body:JSON.stringify({audience,subject:mailSubject,html:mailHtml})});setMsg(`Bulk email complete: ${r.sent}/${r.recipient_count} sent, ${r.failed} failed.`)}catch(e:any){setMsg(e.message)}}
 if(!authorized)return <div className="loadingPanel">Checking administrator access…</div>;
 return <><div className="dashhead"><div><p className="eyebrow darkEye">SUPER_ADMIN</p><h1>Control plane</h1></div><span className="pill">Platform configuration</span></div>{msg&&<p className="notice">{msg}</p>}
 <div className="dashgrid"><section className="panel"><h3>Pricing & entitlements</h3><div className="configGrid">{Object.entries(draft).filter(([k])=>k.startsWith('pricing.')||k.startsWith('pages.')||k.startsWith('credits.')).map(([k,v])=><label key={k}>{k}<input value={v} onChange={e=>setDraft(d=>({...d,[k]:e.target.value}))} onBlur={()=>update(k)}/></label>)}</div></section><section className="panel"><h3>Managed leads</h3><div className="leadTable">{leads.map(l=><div className="leadAdminRow" key={l.id}><div><strong>{l.lead_code}</strong><span>{l.name} · {l.website_type}</span></div><select value={l.status} onChange={e=>leadStatus(l.id,e.target.value)}><option>PENDING</option><option>CLOSED</option><option>NOT_CLOSED</option></select></div>)}{!leads.length&&<div className="emptyState">No managed enquiries yet.</div>}</div></section></div>
 <section className="panel adminWide" id="blog-editor"><div className="panelTitle"><div><h3>Blog publishing</h3><p>Create, edit, publish, unpublish, and delete Zylora Journal posts.</p></div><button className="secondaryButton" onClick={()=>{setEditing(null);setPost(emptyPost)}}>New post</button></div><div className="blogAdminGrid"><form className="adminForm" onSubmit={savePost}><label>Title<input required value={post.title||''} onChange={e=>setPost((p:any)=>({...p,title:e.target.value}))}/></label><label>Slug<input required value={post.slug||''} onChange={e=>setPost((p:any)=>({...p,slug:e.target.value}))}/></label><label>Excerpt<textarea rows={2} value={post.excerpt||''} onChange={e=>setPost((p:any)=>({...p,excerpt:e.target.value}))}/></label><label>Article content<textarea required rows={10} value={post.content||''} onChange={e=>setPost((p:any)=>({...p,content:e.target.value}))}/></label><label>Featured image URL<input value={post.featured_image||''} onChange={e=>setPost((p:any)=>({...p,featured_image:e.target.value||null}))}/></label><label>SEO title<input value={post.seo_title||''} onChange={e=>setPost((p:any)=>({...p,seo_title:e.target.value||null}))}/></label><label>SEO description<textarea rows={2} value={post.seo_description||''} onChange={e=>setPost((p:any)=>({...p,seo_description:e.target.value||null}))}/></label><label>Canonical URL<input value={post.canonical_url||''} onChange={e=>setPost((p:any)=>({...p,canonical_url:e.target.value||null}))}/></label><label>Schedule publication<input type="datetime-local" value={post.publish_at?String(post.publish_at).slice(0,16):''} onChange={e=>setPost((p:any)=>({...p,publish_at:e.target.value?new Date(e.target.value).toISOString():null}))}/></label><div className="rowActions"><button type="submit">{editing?'Save changes':'Create draft'}</button>{editing&&post.publish_at&&<button type="button" onClick={()=>setPostStatus(editing,'SCHEDULED',post.publish_at)}>Schedule</button>}</div></form><div className="blogAdminList">{posts.map(p=><article key={p.id}><div><strong>{p.title}</strong><small>{p.status} · /blog/{p.slug}</small></div><div className="rowActions"><button onClick={()=>editPost(p)}>Edit</button><select value={p.status} onChange={e=>setPostStatus(p.id,e.target.value)}><option>DRAFT</option><option>PUBLISHED</option><option>UNPUBLISHED</option></select><button className="dangerButton" onClick={()=>removePost(p.id)}>Delete</button></div></article>)}{!posts.length&&<div className="emptyState">No posts yet.</div>}</div></div></section>
 <TemplateAdmin/>
 <section className="panel adminWide"><div className="panelTitle"><div><h3>Bulk email</h3><p>Send a campaign to customers, captured leads, managed leads, or all unique recipients.</p></div></div><form className="bulkMail adminForm" onSubmit={sendBulk}><label>Audience<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="USERS">All users</option><option value="LEADS">Website leads</option><option value="MANAGED_LEADS">Managed leads</option><option value="ALL">All unique contacts</option></select></label><label>Subject<input required value={mailSubject} onChange={e=>setMailSubject(e.target.value)}/></label><label>HTML content<textarea required rows={8} value={mailHtml} onChange={e=>setMailHtml(e.target.value)} placeholder="<h1>...</h1>"/></label><button type="submit">Send campaign</button></form></section>
 </>
}
