'use client';
import {FormEvent,useEffect,useState} from 'react';
import {API,api,Site} from '../lib/api';

type Schedule={site_id:number;enabled:boolean;timezone:string;duration_minutes:number;buffer_minutes:number;day_start_minute:number;day_end_minute:number;weekdays:number[]};
type Doc={id:number;name:string;content:string;source_type:string};
type NotificationSettings={whatsapp_number:string|null};
const defaultSchedule=(id:number):Schedule=>({site_id:id,enabled:false,timezone:'Asia/Kolkata',duration_minutes:30,buffer_minutes:15,day_start_minute:540,day_end_minute:1020,weekdays:[0,1,2,3,4]});

export default function EditorClient({siteId}:{siteId:number}){
 const[site,setSite]=useState<Site|null>(null),[schedule,setSchedule]=useState<Schedule>(defaultSchedule(siteId));
 const[docs,setDocs]=useState<Doc[]>([]),[docName,setDocName]=useState('FAQ / business knowledge'),[docText,setDocText]=useState('');
 const[notifications,setNotifications]=useState<NotificationSettings>({whatsapp_number:null});
 const[tab,setTab]=useState<'content'|'design'|'seo'|'leads'|'chatbot'>('content'),[msg,setMsg]=useState(''),[preview,setPreview]=useState<'desktop'|'tablet'|'mobile'>('desktop');
 useEffect(()=>{Promise.all([api<Site>(`/sites/${siteId}`),api<Schedule>(`/scheduling/config/${siteId}`),api<Doc[]>(`/sites/${siteId}/documents`),api<NotificationSettings>('/notifications/settings')]).then(([s,c,d,n])=>{setSite(s);setSchedule(c);setDocs(d);setNotifications(n)}).catch((e:any)=>setMsg(e.message))},[siteId]);
 const content=site?.content||{};
 async function save(){if(!site)return;setMsg('Saving…');try{const[s,,n]=await Promise.all([api<Site>(`/sites/${site.id}`,{method:'PATCH',body:JSON.stringify({name:site.name,content:site.content,seo:site.seo,theme:site.theme})}),api('/scheduling/config',{method:'PUT',body:JSON.stringify(schedule)}),api<NotificationSettings>('/notifications/settings',{method:'PUT',body:JSON.stringify(notifications)})]);setSite(s);setNotifications(n);setMsg('Saved')}catch(e:any){setMsg(e.message)}}
 async function publish(){if(!site)return;setMsg('Publishing…');try{await save();const p:any=await api(`/publishing/sites/${site.id}`,{method:'POST'});await api(`/sites/${site.id}/make-live`,{method:'POST'});setMsg(`Published${p.public_url?` — ${p.public_url}`:''}`)}catch(e:any){setMsg(e.message)}}
 function setContent(k:string,v:any){setSite(s=>s?{...s,content:{...s.content,[k]:v}}:s)}function setSeo(k:string,v:string){setSite(s=>s?{...s,seo:{...s.seo,[k]:v}}:s)}
 async function addPastedDoc(e:FormEvent){e.preventDefault();if(!docText.trim())return;try{const d=await api<Doc>(`/sites/${siteId}/documents`,{method:'POST',body:JSON.stringify({name:docName||'Knowledge',content:docText})});setDocs(x=>[d,...x]);setDocText('');setMsg('Chatbot knowledge added.')}catch(e:any){setMsg(e.message)}}
 async function uploadDoc(file:File){const fd=new FormData();fd.append('file',file);setMsg('Uploading knowledge…');try{const res=await fetch(`${API}/sites/${siteId}/documents/upload`,{method:'POST',credentials:'include',body:fd});const text=await res.text();const body=text?JSON.parse(text):{};if(!res.ok)throw new Error(body.detail||`Upload failed (${res.status})`);setDocs(x=>[body,...x]);setMsg('Knowledge file uploaded.')}catch(e:any){setMsg(e.message)}}
 async function removeDoc(id:number){if(!confirm('Remove this chatbot document?'))return;try{await api(`/sites/${siteId}/documents/${id}`,{method:'DELETE'});setDocs(x=>x.filter(d=>d.id!==id));setMsg('Knowledge removed.')}catch(e:any){setMsg(e.message)}}
 if(!site)return <div className="editorLoading">{msg||'Loading editor…'}</div>;
 return <div className="editor"><header className="editorTop"><div><b>{site.name}</b><span>{site.state}</span></div><div className="previewSwitch"><button onClick={()=>setPreview('desktop')} className={preview==='desktop'?'active':''}>Desktop</button><button onClick={()=>setPreview('tablet')} className={preview==='tablet'?'active':''}>Tablet</button><button onClick={()=>setPreview('mobile')} className={preview==='mobile'?'active':''}>Mobile</button></div><div><button className="secondaryAction" onClick={save}>Save</button><button className="primaryAction" onClick={publish}>Publish</button></div></header><div className="editorBody"><aside className="editorPanel"><div className="editorTabs"><button className={tab==='content'?'active':''} onClick={()=>setTab('content')}>Content</button><button className={tab==='design'?'active':''} onClick={()=>setTab('design')}>Design</button><button className={tab==='seo'?'active':''} onClick={()=>setTab('seo')}>SEO</button><button className={tab==='leads'?'active':''} onClick={()=>setTab('leads')}>Leads</button><button className={tab==='chatbot'?'active':''} onClick={()=>setTab('chatbot')}>Chatbot</button></div>
 {tab==='content'&&<div className="fieldStack"><label>Site name<input value={site.name} onChange={e=>setSite({...site,name:e.target.value})}/></label><label>Business name<input value={content.businessName||''} onChange={e=>setContent('businessName',e.target.value)} placeholder="Your business"/></label><label>Headline<input value={content.headline||''} onChange={e=>setContent('headline',e.target.value)} placeholder="A clear, compelling headline"/></label><label>Description<textarea value={content.description||''} onChange={e=>setContent('description',e.target.value)} rows={5}/></label><label>Email<input value={content.email||''} onChange={e=>setContent('email',e.target.value)}/></label><label>Phone<input value={content.phone||''} onChange={e=>setContent('phone',e.target.value)}/></label><label>Address<input value={content.address||''} onChange={e=>setContent('address',e.target.value)}/></label><label>Hero image URL<input value={content.heroImage||''} onChange={e=>setContent('heroImage',e.target.value)} placeholder="https://…"/></label><label>Image alt text<input value={content.imageAlt||''} onChange={e=>setContent('imageAlt',e.target.value)} placeholder="Describe the image"/></label><label>Services (one per line)<textarea rows={5} value={(content.services||[]).map((x:any)=>typeof x==='string'?x:x.name||'').join('\n')} onChange={e=>setContent('services',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}/></label></div>}
 {tab==='design'&&<div className="fieldStack"><label>Accent color<input type="color" value={site.theme?.accent||'#6937ff'} onChange={e=>setSite({...site,theme:{...site.theme,accent:e.target.value}})}/></label><label>Radius<select value={site.theme?.radius||'soft'} onChange={e=>setSite({...site,theme:{...site.theme,radius:e.target.value}})}><option value="sharp">Sharp</option><option value="soft">Soft</option><option value="round">Round</option></select></label><p className="mutedCopy">Template structure stays protected while visual tokens and content remain editable.</p></div>}
 {tab==='seo'&&<div className="fieldStack"><label>SEO title<input value={site.seo?.title||''} onChange={e=>setSeo('title',e.target.value)}/></label><label>Meta description<textarea value={site.seo?.description||''} onChange={e=>setSeo('description',e.target.value)} rows={4}/></label><label>Canonical URL<input value={site.seo?.canonical||''} onChange={e=>setSeo('canonical',e.target.value)}/></label><label>Open Graph image URL<input value={site.seo?.ogImage||''} onChange={e=>setSeo('ogImage',e.target.value)}/></label></div>}
 {tab==='leads'&&<div className="fieldStack">
  <div><strong>WhatsApp lead notifications</strong><p className="mutedCopy" style={{marginTop:6}}>Receive a WhatsApp message when any of your published sites captures a lead. This account-level number is never shown to visitors.</p></div>
  <label>WhatsApp number<input type="tel" inputMode="tel" autoComplete="tel" value={notifications.whatsapp_number||''} onChange={e=>setNotifications({whatsapp_number:e.target.value||null})} placeholder="+919876543210" maxLength={32} aria-describedby="whatsapp-format"/></label>
  <small id="whatsapp-format" className="mutedCopy">Use international format with country code, for example +919876543210. Leave blank to disable notifications.</small>
  <label className="toggleLabel"><input type="checkbox" checked={schedule.enabled} onChange={e=>setSchedule({...schedule,enabled:e.target.checked})}/> Enable visitor appointment booking</label>
  <label>Timezone<input value={schedule.timezone} onChange={e=>setSchedule({...schedule,timezone:e.target.value})}/></label>
  <label>Appointment duration<select value={schedule.duration_minutes} onChange={e=>setSchedule({...schedule,duration_minutes:Number(e.target.value)})}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={45}>45 minutes</option><option value={60}>60 minutes</option></select></label>
  <label>Buffer<select value={schedule.buffer_minutes} onChange={e=>setSchedule({...schedule,buffer_minutes:Number(e.target.value)})}><option value={0}>None</option><option value={10}>10 minutes</option><option value={15}>15 minutes</option><option value={30}>30 minutes</option></select></label>
  <label>Start time<input type="time" value={`${String(Math.floor(schedule.day_start_minute/60)).padStart(2,'0')}:${String(schedule.day_start_minute%60).padStart(2,'0')}`} onChange={e=>{const[h,m]=e.target.value.split(':').map(Number);setSchedule({...schedule,day_start_minute:h*60+m})}}/></label>
  <label>End time<input type="time" value={`${String(Math.floor(schedule.day_end_minute/60)).padStart(2,'0')}:${String(schedule.day_end_minute%60).padStart(2,'0')}`} onChange={e=>{const[h,m]=e.target.value.split(':').map(Number);setSchedule({...schedule,day_end_minute:h*60+m})}}/></label>
  <p className="mutedCopy">Every published site automatically gets the mandatory chatbot and proactive lead form. The lead form opens after 10 seconds or when a visitor reaches the end of the page. Enable appointment booking here to show available calendar slots after capture.</p>
 </div>}
 {tab==='chatbot'&&<div className="fieldStack"><div><strong>AI chatbot knowledge</strong><p className="mutedCopy" style={{marginTop:6}}>Ground the site assistant with FAQs, policies, pricing sheets and service details. The assistant is instructed to answer only from your site content and these documents.</p></div><form className="chatbotKnowledgeForm" onSubmit={addPastedDoc}><label>Document name<input value={docName} onChange={e=>setDocName(e.target.value)}/></label><label>Paste knowledge<textarea rows={8} value={docText} onChange={e=>setDocText(e.target.value)} placeholder="Paste FAQs, pricing, policies, service details…"/></label><button className="primaryAction" type="submit">Add knowledge</button></form><label>Upload text document<input type="file" accept=".txt,.md,.csv,.json,.html,.htm,text/plain,text/markdown,text/csv,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)uploadDoc(f);e.currentTarget.value=''}}/></label><div className="knowledgeList">{docs.map(d=><article key={d.id}><div><strong>{d.name}</strong><small>{d.source_type} · {d.content.length.toLocaleString()} characters</small></div><button className="dangerButton" onClick={()=>removeDoc(d.id)}>Remove</button></article>)}{!docs.length&&<div className="emptyState">No knowledge documents yet. Site content is still available to the chatbot.</div>}</div><p className="mutedCopy">Each successful AI reply consumes one chatbot credit according to the existing lead-credit → AI-credit fallback. Sessions are capped to control cost.</p></div>}
 {msg&&<p className="notice">{msg}</p>}</aside><section className={`sitePreview ${preview}`} style={{'--preview-accent':site.theme?.accent||'#6937ff'} as any}><div className="previewPage"><nav><strong>{content.businessName||site.name}</strong><span>About&nbsp;&nbsp; Services&nbsp;&nbsp; Contact</span></nav><div className="previewHero"><small>BUILT WITH ZYLORA</small><h1>{content.headline||'Give your business a website worth remembering.'}</h1><p>{content.description||'Edit the content panel to replace this preview copy with your real business information.'}</p><button>Get in touch</button></div><div className="previewCards"><article><b>01</b><h3>Designed for conversion</h3></article><article><b>02</b><h3>Responsive by default</h3></article><article><b>03</b><h3>SEO controls built in</h3></article></div><footer>{content.email||'hello@yourbusiness.com'} · {content.phone||'+91 00000 00000'}</footer></div></section></div></div>
}
