'use client';
import {useEffect,useMemo,useState} from 'react';
import {api} from '../lib/api';

type T={key:string;family:string;quality_tier:string;page_count:number;visible:boolean;featured:boolean;display_name:string;description:string;tags:string[];preview_image?:string|null;sort_order:number};
export default function TemplateAdmin(){
 const[list,setList]=useState<T[]>([]),[q,setQ]=useState(''),[msg,setMsg]=useState(''),[showHidden,setShowHidden]=useState(false);
 useEffect(()=>{api<T[]>('/admin/templates').then(setList).catch((e:any)=>setMsg(e.message))},[]);
 const shown=useMemo(()=>list.filter(t=>(showHidden||t.visible)&&(`${t.key} ${t.display_name} ${t.family} ${t.tags.join(' ')}`).toLowerCase().includes(q.toLowerCase())).slice(0,180),[list,q,showHidden]);
 async function patch(key:string,changes:Partial<T>){const prev=list;setList(xs=>xs.map(x=>x.key===key?{...x,...changes}:x));try{const saved=await api<T>(`/admin/templates/${encodeURIComponent(key)}`,{method:'PATCH',body:JSON.stringify(changes)});setList(xs=>xs.map(x=>x.key===key?saved:x));setMsg('Template saved.')}catch(e:any){setList(prev);setMsg(`Template save failed: ${e.message}`)}}
 async function hideVariants(){if(!confirm('Hide every template not currently marked premium? Files are kept and can be restored individually.'))return;try{const r=await api<any>('/admin/templates/bulk-hide-non-premium',{method:'POST'});setList(await api<T[]>('/admin/templates'));setMsg(`${r.hidden} non-premium templates hidden.`)}catch(e:any){setMsg(e.message)}}
 return <section className="panel adminWide"><div className="panelTitle"><div><h3>Template catalogue control</h3><p>Control visibility, featured placement, quality status and customer-facing metadata without touching source code.</p></div><button className="secondaryButton" onClick={hideVariants}>Hide non-premium</button></div>{msg&&<p className="notice">{msg}</p>}<div className="templateAdminToolbar"><input placeholder="Search templates…" value={q} onChange={e=>setQ(e.target.value)}/><label><input type="checkbox" checked={showHidden} onChange={e=>setShowHidden(e.target.checked)}/> Show hidden</label><span>{list.filter(x=>x.visible).length.toLocaleString()} visible · {list.filter(x=>x.featured).length} featured</span></div><div className="templateAdminList">{shown.map(t=><article key={t.key}><div className="templateAdminIdentity"><strong>{t.display_name}</strong><small>{t.key} · {t.family} · {t.page_count} pages · {t.quality_tier}</small></div><div className="templateAdminChecks"><label><input type="checkbox" checked={t.visible} onChange={e=>patch(t.key,{visible:e.target.checked})}/> Visible</label><label><input type="checkbox" checked={t.featured} onChange={e=>patch(t.key,{featured:e.target.checked})}/> Featured</label></div><label>Name<input value={t.display_name} onChange={e=>setList(xs=>xs.map(x=>x.key===t.key?{...x,display_name:e.target.value}:x))} onBlur={()=>patch(t.key,{display_name:t.display_name})}/></label><label>Family<input value={t.family} onChange={e=>setList(xs=>xs.map(x=>x.key===t.key?{...x,family:e.target.value}:x))} onBlur={()=>patch(t.key,{family:t.family})}/></label><label>Quality tier<select value={t.quality_tier} onChange={e=>patch(t.key,{quality_tier:e.target.value})}><option value="premium">Premium</option><option value="variant">Variant</option><option value="experimental">Experimental</option></select></label><label>Preview image URL<input value={t.preview_image||''} onChange={e=>setList(xs=>xs.map(x=>x.key===t.key?{...x,preview_image:e.target.value}:x))} onBlur={()=>patch(t.key,{preview_image:t.preview_image||null})}/></label><label>Description<textarea rows={2} value={t.description} onChange={e=>setList(xs=>xs.map(x=>x.key===t.key?{...x,description:e.target.value}:x))} onBlur={()=>patch(t.key,{description:t.description})}/></label><label>Tags<input value={t.tags.join(', ')} onChange={e=>setList(xs=>xs.map(x=>x.key===t.key?{...x,tags:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)}:x))} onBlur={()=>patch(t.key,{tags:t.tags})}/></label></article>)}{!shown.length&&<div className="emptyState">No templates match this view.</div>}</div></section>
}
