import React from 'react';
import {Node, useStudio} from '../store';

type Item={label:string;category:string;type:string;kind?:string;tags?:string[];css?:Record<string,string|undefined>;content?:Record<string,any>;subtree?:{rootId:string;nodes:Record<string,Node>}};
type PanelMode='sections'|'elements'|'text'|'draw';
const item=(label:string,category:string,type:string,css:Record<string,string|undefined>={},content:Record<string,any>={},kind?:string,tags:string[]=[]):Item=>({label,category,type,css,content,kind,tags:[label.toLowerCase(),category.toLowerCase(),...tags]});
const shapeNames=['Rectangle','Rounded rectangle','Square','Circle','Ellipse','Triangle','Right triangle','Diamond','Pentagon','Hexagon','Octagon','Star','Star 4','Star 5','Star 6','Starburst','Heart','Pill','Parallelogram','Trapezoid','Speech bubble','Arrow left','Arrow right','Arrow up','Arrow down','Chevron','Cross','Ring','Semicircle','Quarter circle','Blob','Blob 2','Blob 3'];
const shapeClip=(label:string)=>{const lower=label.toLowerCase();if(lower==='triangle')return 'polygon(50% 0,100% 100%,0 100%)';if(lower==='right triangle')return 'polygon(0 0,100% 100%,0 100%)';if(lower==='diamond')return 'polygon(50% 0,100% 50%,50% 100%,0 50%)';if(lower==='parallelogram')return 'polygon(25% 0,100% 0,75% 100%,0 100%)';if(lower==='trapezoid')return 'polygon(20% 0,80% 0,100% 100%,0 100%)';if(lower.includes('arrow right'))return 'polygon(0 25%,65% 25%,65% 0,100% 50%,65% 100%,65% 75%,0 75%)';if(lower.includes('arrow left'))return 'polygon(0 50%,35% 0,35% 25%,100% 25%,100% 75%,35% 75%,35% 100%)';if(lower.includes('arrow up'))return 'polygon(50% 0,100% 45%,72% 45%,72% 100%,28% 100%,28% 45%,0 45%)';if(lower.includes('arrow down'))return 'polygon(28% 0,72% 0,72% 55%,100% 55%,50% 100%,0 55%,28% 55%)';if(lower==='chevron')return 'polygon(0 0,50% 50%,0 100%,30% 100%,80% 50%,30% 0)';if(lower==='cross')return 'polygon(35% 0,65% 0,65% 35%,100% 35%,100% 65%,65% 65%,65% 100%,35% 100%,35% 65%,0 65%,0 35%,35% 35%)';if(lower==='semicircle')return 'ellipse(50% 50% at 50% 100%)';if(lower==='quarter circle')return 'ellipse(100% 100% at 0 100%)';if(lower.startsWith('blob'))return 'polygon(12% 20%,38% 5%,72% 12%,94% 38%,88% 72%,60% 94%,24% 86%,5% 55%)';return undefined;};
const shapes=shapeNames.map((label,index)=>item(label,'Shapes','container',{width:index<3?'220px':'170px',height:index<3?'150px':'170px',background:['#111827','#7c3aed','#06b6d4','#f59e0b','#ef4444'][index%5],borderRadius:label.includes('Rounded')||label==='Pill'?'24px':label==='Circle'||label==='Ellipse'||label==='Ring'?'50%':undefined,clipPath:shapeClip(label),boxShadow:'0 8px 18px rgba(15,23,42,.12)'},{},'shape',['geometry','primitive']));
const lines=[['Straight line','solid'],['Arrow line','arrow'],['Double arrow','double-arrow'],['Dotted line','dotted'],['Dashed line','dashed']].map(([label,kind])=>item(label,'Lines','divider',{width:'260px',height:kind==='dotted'||kind==='dashed'?'3px':'2px',background:'#111827',borderStyle:kind==='dotted'?'dotted':kind==='dashed'?'dashed':'solid',borderWidth:'0 0 2px 0'},{},'line',['divider','stroke',kind]));
const frameSpecs:[string,string,string|undefined][]=[['Square frame','1 / 1',undefined],['Portrait frame','3 / 4',undefined],['Landscape frame','4 / 3',undefined],['Circle frame','1 / 1','ellipse(50% 50% at 50% 50%)'],['Rounded frame','4 / 3',undefined],['Rounded square','1 / 1',undefined],['Phone frame','9 / 19.5',undefined],['Tablet frame','4 / 3',undefined],['Desktop frame','16 / 10',undefined],['Widescreen','16 / 9',undefined],['Vertical story','9 / 16',undefined],['Arch frame','3 / 4','path("M 0 100 L 0 35 A 50 50 0 0 1 100 35 L 100 100 Z")'],['Capsule frame','2 / 1',undefined],['Heart frame','1 / 1','polygon(50% 95%,8% 55%,5% 25%,22% 5%,50% 25%,78% 5%,95% 25%,92% 55%)'],['Diamond frame','1 / 1','polygon(50% 0,100% 50%,50% 100%,0 50%)'],['Triangle frame','1 / 1','polygon(50% 0,100% 100%,0 100%)'],['Hexagon frame','1 / 1','polygon(25% 5%,75% 5%,100% 50%,75% 95%,25% 95%,0 50%)'],['Blob frame','1 / 1','polygon(12% 20%,38% 5%,72% 12%,94% 38%,88% 72%,60% 94%,24% 86%,5% 55%)']];
const frames=frameSpecs.map(([label,ratio,clip],index)=>item(label,'Frames','image',{width:index%3===0?'260px':index%3===1?'220px':'360px',height:index%3===0?'260px':index%3===1?'320px':'220px',aspectRatio:ratio,objectFit:'cover',background:'#e2e8f0',borderRadius:label.includes('Circle')||label.includes('Capsule')?'50%':label.includes('Rounded')?'28px':undefined,clipPath:clip},{src:'',alt:'',crop:{x:0,y:0,scale:1}},'image-frame',['mask','media','photo']));
const icons=['Spark','Plus','Arrow','Check','Heart','Star','Search','Menu','X','Play','Mail','Phone','Globe','Calendar','Map pin','Camera'].map(label=>item(label,'Icons','icon',{width:'56px',height:'56px',display:'grid',placeItems:'center',borderRadius:'14px',background:'#111827',color:'#fff',fontSize:'24px'},{text:({'Heart':'♥','Star':'★','Check':'✓','Plus':'+','X':'×','Arrow':'→','Play':'▶','Menu':'≡','Mail':'✉','Phone':'☎','Globe':'◎','Calendar':'▣','Map pin':'⌖','Camera':'◉'} as Record<string,string>)[label]||'✦'},'icon',['symbol','interface']));
const stickers=['Star burst','Highlight','Scribble','Underline','Tape','Badge','Burst','Circle mark','Doodle arrow','Sparkle','Label','Speech shape'].map((label,index)=>item(label,'Stickers','container',{width:'140px',height:'70px',background:['#fde68a','#bfdbfe','#fbcfe8','#bbf7d0'][index%4],borderRadius:'18px',transform:`rotate(${index%2?'4':'-4'}deg)`,clipPath:index%3===0?'polygon(4% 20%,35% 14%,50% 0,65% 14%,96% 20%,86% 50%,96% 80%,65% 86%,50% 100%,35% 86%,4% 80%,14% 50%)':undefined},{text:label},'sticker',['decorative','mark','accent']));
const buttons=[item('Button','Buttons','button',{width:'150px',height:'48px',display:'grid',placeItems:'center',borderRadius:'10px',background:'#111827',color:'#fff',fontWeight:'700'},{text:'Button',href:'#'},'button',['cta','action'])];
const textItem=item('Text','Text','text',{width:'360px',fontSize:'32px',lineHeight:'1.15',fontWeight:'650',color:'#111827'},{text:'Add your text'},'text',['copy','typography']);
const full=(id:string,type:string,parentId:string|null,children:string[],content:Record<string,any>,css:Record<string,string>,name:string,kind?:string):Node=>({id,type,parentId,children,content,style:{css,tokens:{}},layout:{},responsiveOverrides:{},visibility:'visible',bindings:{},accessibility:{},interactions:[],metadata:{displayName:name,kind:kind||type}});
const cardItem=():Item=>{const root='card_root',image='card_image',title='card_title',copy='card_copy',button='card_button';const nodes:Record<string,Node>={
 [root]:full(root,'container',null,[image,title,copy,button],{}, {position:'relative',width:'360px',height:'430px',background:'#ffffff',border:'1px solid #dbe2ea',borderRadius:'24px',boxShadow:'0 18px 42px rgba(15,23,42,.12)',overflow:'hidden'},'Card','card'),
 [image]:full(image,'image',root,[],{src:'',alt:'',crop:{x:0,y:0,scale:1}},{position:'absolute',left:'20px',top:'20px',width:'320px',height:'190px',objectFit:'cover',background:'#e2e8f0',borderRadius:'16px'},'Card image','image-frame'),
 [title]:full(title,'text',root,[],{text:'Card title'},{position:'absolute',left:'24px',top:'232px',width:'312px',height:'38px',fontSize:'26px',fontWeight:'700',lineHeight:'1.15',color:'#111827'},'Card title','text'),
 [copy]:full(copy,'text',root,[],{text:'Add a short description that helps visitors understand this card.'},{position:'absolute',left:'24px',top:'282px',width:'312px',height:'52px',fontSize:'15px',lineHeight:'1.45',color:'#475569'},'Card description','text'),
 [button]:full(button,'button',root,[],{text:'Learn more',href:'#'},{position:'absolute',left:'24px',top:'354px',width:'138px',height:'46px',display:'grid',placeItems:'center',background:'#111827',color:'#ffffff',borderRadius:'10px',fontWeight:'700'},'Card button','button'),
};return{label:'Card',category:'Cards',type:'container',tags:['card','content','image','button','website'],subtree:{rootId:root,nodes}}};
const cards=[cardItem()];
const gridItem=(label:string,columns:string,rows:string,count:number,areas?:string):Item=>{const root='grid_root',cells=Array.from({length:count},(_,i)=>`grid_${i}`);const css:Record<string,string>={position:'relative',display:'grid',gridTemplateColumns:columns,gridTemplateRows:rows,gap:'12px',width:'620px',height:'420px'};if(areas)css.gridTemplateAreas=areas;const nodes:Record<string,Node>={[root]:full(root,'grid',null,cells,{},css,label,'grid')};cells.forEach(id=>nodes[id]=full(id,'image',root,[],{src:'',alt:'',crop:{x:0,y:0,scale:1}},{width:'100%',height:'100%',objectFit:'cover',background:'#e2e8f0',minHeight:'120px'},'Image frame','image-frame'));return {label,category:'Grids',type:'grid',tags:[label.toLowerCase(),'gallery','layout','media'],subtree:{rootId:root,nodes}}};
const grids=[gridItem('2 columns','repeat(2, 1fr)','repeat(1, 1fr)',2),gridItem('3 columns','repeat(3, 1fr)','repeat(1, 1fr)',3),gridItem('4 columns','repeat(4, 1fr)','repeat(1, 1fr)',4),gridItem('2 rows','repeat(1, 1fr)','repeat(2, 1fr)',2),gridItem('3 rows','repeat(1, 1fr)','repeat(3, 1fr)',3),gridItem('2×2','repeat(2, 1fr)','repeat(2, 1fr)',4),gridItem('3×2','repeat(3, 1fr)','repeat(2, 1fr)',6),gridItem('3×3','repeat(3, 1fr)','repeat(3, 1fr)',9),gridItem('70 / 30','70% 30%','repeat(1, 1fr)',2),gridItem('30 / 70','30% 70%','repeat(1, 1fr)',2),gridItem('Large left + stacked right','2fr 1fr','1fr 1fr',3,'"large smallTop" "large smallBottom"'),gridItem('Stacked left + large right','1fr 2fr','1fr 1fr',3,'"smallTop large" "smallBottom large"'),gridItem('Magazine','2fr 1fr 1fr','1fr 1fr',4,'"feature sideTop sideTop" "feature sideBottom sideBottom"'),gridItem('Gallery strip','repeat(5, 1fr)','1fr',5),gridItem('Hero + thumbnails','3fr 1fr','repeat(3, 1fr)',4,'"hero thumb1" "hero thumb2" "hero thumb3"')];
const all=[...shapes,...lines,...buttons,...cards,...frames,...grids,...stickers,...icons];
const safeCss=(css?:Record<string,string|undefined>):Record<string,string>=>Object.fromEntries(Object.entries(css||{}).filter((entry):entry is [string,string]=>typeof entry[1]==='string'));
const matches=(x:Item,query:string)=>{const needle=query.trim().toLowerCase();return !needle||[x.label,x.category,...(x.tags||[])].some(value=>value.toLowerCase().includes(needle));};
const storedLabels=(key:string)=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[]}catch{return[]}};
const persistLabels=(key:string,labels:string[])=>{try{localStorage.setItem(key,JSON.stringify(labels))}catch{/* preferences are optional */}};

export function AddPanel({mode='elements'}:{mode?:PanelMode}){
  const {dispatch}=useStudio();const [query,setQuery]=React.useState('');const [expanded,setExpanded]=React.useState<Record<string,boolean>>({});const [recent,setRecent]=React.useState<string[]>(()=>storedLabels('zylora-studio-recent-primitives').slice(0,8));const [favorites,setFavorites]=React.useState<string[]>(()=>storedLabels('zylora-studio-favorite-primitives'));
  const drag=(e:React.DragEvent,payload:any)=>{e.dataTransfer.setData('application/x-zylora-node',JSON.stringify(payload));e.dataTransfer.effectAllowed='copy';(window as any).__zyloraDraggingNode=payload};
  const insert=(x:Item)=>{setRecent(previous=>{const next=[x.label,...previous.filter(label=>label!==x.label)].slice(0,8);persistLabels('zylora-studio-recent-primitives',next);return next});if(x.subtree)dispatch({type:'INSERT_SUBTREE',payload:x.subtree});else dispatch({type:'INSERT_NODE',payload:{node:{type:x.type,content:x.content||{},style:{css:safeCss(x.css),tokens:{}},metadata:{displayName:x.label,kind:x.kind||x.category.toLowerCase()}}}})};
  const toggleFavorite=(label:string)=>setFavorites(previous=>{const next=previous.includes(label)?previous.filter(item=>item!==label):[...previous,label];persistLabels('zylora-studio-favorite-primitives',next);return next});
  const card=(x:Item)=><article key={`${x.category}-${x.label}`} className={`asset-card primitive-${x.category.toLowerCase().replace(/\W/g,'-')}`} draggable onDragStart={e=>drag(e,x.subtree?{label:x.label,subtree:x.subtree}:{label:x.label,type:x.type,node:{type:x.type,content:x.content||{},style:{css:safeCss(x.css),tokens:{}},metadata:{displayName:x.label,kind:x.kind||x.category.toLowerCase()}}})} onDragEnd={()=>delete (window as any).__zyloraDraggingNode}><button className={`asset-add-button${x===textItem?' add-text-action':''}`} onClick={()=>insert(x)} aria-label={`Add ${x.label}`}><span className="asset-preview"><i/></span><b>{x.label}</b><small>Add {x.label.toLowerCase()}</small></button><button type="button" className={`asset-favorite${favorites.includes(x.label)?' active':''}`} aria-label={`${favorites.includes(x.label)?'Remove from':'Add to'} favorites: ${x.label}`} title={`${favorites.includes(x.label)?'Remove from':'Add to'} favorites`} onClick={event=>{event.stopPropagation();toggleFavorite(x.label)}}>★</button></article>;
  const search=<div className="asset-search"><span aria-hidden="true">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search elements" aria-label="Search elements"/></div>;
  if(mode==='sections')return <div className="studio-panel blank-asset-panel"><div className="panel-intro"><b>Sections</b><span>Root-level artboards for the current page.</span></div><button className="add-text-action" onClick={()=>dispatch({type:'ADD_SECTION'})}>＋ <span>Add blank section</span></button><p className="beginner-tip">Sections are always inserted below the current section. Build them with primitives.</p></div>;
  if(mode==='text')return <div className="studio-panel blank-asset-panel"><div className="panel-intro"><b>Text</b><span>One flexible text primitive; formatting defines the role.</span></div>{search}<div className="asset-grid">{[textItem].filter(x=>matches(x,query)).map(card)}</div></div>;
  const categories=mode==='draw'?['Shapes','Lines','Stickers']:['Shapes','Lines','Frames','Grids','Cards','Stickers','Icons','Buttons'];const favoriteItems=favorites.map(label=>all.find(x=>x.label===label)).filter((x):x is Item=>!!x&&matches(x,query));const favoriteLabels=new Set(favoriteItems.map(x=>x.label));const recentItems=recent.map(label=>all.find(x=>x.label===label)).filter((x):x is Item=>!!x&&matches(x,query)&&!favoriteLabels.has(x.label));const featuredLabels=new Set([...favoriteLabels,...recentItems.map(x=>x.label)]);
  return <div className="studio-panel blank-asset-panel"><div className="panel-intro"><b>Elements</b><span>Click or drag a primitive onto the canvas. Star an item to keep it in Favorites.</span></div>{search}{!query&&favoriteItems.length>0&&<section><h3>Favorites <small>{favoriteItems.length}</small></h3><div className="asset-grid">{favoriteItems.map(card)}</div></section>}{!query&&recentItems.length>0&&<section><h3>Recently used <small>{recentItems.length}</small></h3><div className="asset-grid">{recentItems.map(card)}</div></section>}{categories.map(category=>{const items=all.filter(x=>x.category===category&&matches(x,query)&&(query||!featuredLabels.has(x.label)));const shown=expanded[category]||query?items:items.slice(0,12);return <section key={category}><h3>{category}<small> {items.length}</small></h3><div className="asset-grid">{shown.map(card)}</div>{items.length>shown.length&&<button className="see-all" onClick={()=>setExpanded(previous=>({...previous,[category]:true}))}>See all</button>}</section>})}</div>;
}
