import React from 'react';import {useStudio} from '../store';
export function AssetsPanel(){
 const {dispatch}=useStudio();const siteId=(window as any).ZYLORA_STUDIO_CONTEXT?.siteId;const csrf=(window as any).ZYLORA_STUDIO_CONTEXT?.csrfToken;const [items,setItems]=React.useState<any[]>([]),[search,setSearch]=React.useState(''),[busy,setBusy]=React.useState(false),[message,setMessage]=React.useState(''),[tab,setTab]=React.useState<'Images'|'Videos'|'Audio'|'Folders'>('Images');
 const load=React.useCallback(()=>siteId&&fetch(`/api/sites/${siteId}/assets`).then(r=>r.ok?r.json():Promise.reject()).then(d=>setItems(d.items||[])).catch(()=>setMessage('Assets could not be loaded.')),[siteId]);React.useEffect(()=>{load()},[load]);
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setBusy(true);setMessage('Uploading…');for(const file of Array.from(files)){const body=new FormData();body.append('file',file);const r=await fetch(`/api/sites/${siteId}/assets`,{method:'POST',headers:{'X-CSRF-Token':csrf},body});if(!r.ok){setMessage(`Upload failed: ${file.name}`);setBusy(false);return}}setBusy(false);setMessage('Upload complete');load()};
 const record=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true}),chunks:Blob[]=[];const recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.start();setMessage('Recording… click again is not required.');await new Promise(resolve=>setTimeout(resolve,3000));recorder.stop();await new Promise(resolve=>recorder.addEventListener('stop',resolve,{once:true}));stream.getTracks().forEach(track=>track.stop());const file=new File([new Blob(chunks,{type:recorder.mimeType||'video/webm'})],`studio-recording-${Date.now()}.webm`,{type:recorder.mimeType||'video/webm'});const transfer=new DataTransfer();transfer.items.add(file);await upload(transfer.files);setTab('Videos')}catch{setMessage('Camera access was not granted. You can upload a file instead.')}};
 const insert=(a:any)=>dispatch({type:'INSERT_NODE',payload:{node:{type:String(a.mime_type||'').startsWith('video/')?'video':'image',content:{src:a.url||`/media/${a.id}/${encodeURIComponent(a.filename||a.original_filename||'asset')}`,asset_id:a.id,alt:a.alt_text||''},style:{css:{width:'320px',height:'220px',objectFit:'cover'},tokens:{}},metadata:{displayName:a.original_filename||a.filename||'Asset'}}}});
 const visible=items.filter(a=>{const mime=String(a.mime_type||'');const matchesTab=tab==='Images'?mime.startsWith('image/'):tab==='Videos'?mime.startsWith('video/'):tab==='Audio'?mime.startsWith('audio/'):false;return matchesTab&&String(a.original_filename||a.filename||'').toLowerCase().includes(search.toLowerCase())});
 return <div className="studio-panel assets-panel reference-panel"><div className="reference-search compact"><b>⌕</b><input aria-label="Search assets" placeholder="Search keywords, tags, colour" value={search} onChange={e=>setSearch(e.target.value)}/></div><label className={`asset-upload-button ${busy?'busy':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files)}}><input type="file" multiple accept="image/*,video/*,.pdf" onChange={e=>upload(e.target.files)}/><b>{busy?'Uploading…':'Upload files'}</b></label><button className="record-button" onClick={record}>Record yourself</button>{message&&<p className="panel-message">{message}</p>}<div className="asset-tabs" role="tablist">{(['Images','Videos','Audio','Folders'] as const).map(name=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{name}</button>)}</div><div className="asset-grid">{visible.map(a=><button key={a.id} onClick={()=>insert(a)}><span className="asset-thumb">{String(a.mime_type||'').startsWith('image/')?<img src={a.url||`/media/${a.id}/${encodeURIComponent(a.filename||a.original_filename||'asset')}`} alt=""/>:'▶'}</span><small>{a.original_filename||a.filename}</small></button>)}</div>{!items.length&&<div className="empty-state"><b>Your uploads appear here</b><p>Upload an image, then click it or drag it onto the page.</p></div>}</div>;
}
