import React from 'react';import {useStudio} from '../store';
export function AssetsPanel(){
 const {state,dispatch}=useStudio();const siteId=(window as any).ZYLORA_STUDIO_CONTEXT?.siteId;const csrf=(window as any).ZYLORA_STUDIO_CONTEXT?.csrfToken;const [items,setItems]=React.useState<any[]>([]),[search,setSearch]=React.useState(''),[busy,setBusy]=React.useState(false),[message,setMessage]=React.useState('');
 const load=React.useCallback(()=>siteId&&fetch(`/api/sites/${siteId}/assets`).then(r=>r.ok?r.json():Promise.reject()).then(d=>setItems(d.items||[])).catch(()=>setMessage('Assets could not be loaded.')),[siteId]);React.useEffect(()=>{load()},[load]);
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setBusy(true);setMessage('Uploading…');for(const file of Array.from(files)){const body=new FormData();body.append('file',file);const r=await fetch(`/api/sites/${siteId}/assets`,{method:'POST',headers:{'X-CSRF-Token':csrf},body});const d=await r.json().catch(()=>({}));if(!r.ok){const detail=d?.detail;setMessage(typeof detail==='string'?detail:(detail?.message||`Upload failed for ${file.name} (${r.status})`));setBusy(false);return}}setBusy(false);setMessage('Upload complete');load()};
 const insert=(a:any)=>{const selected=state.selectedNodeIds.length===1?state.document?.pages[state.currentPageId]?.nodes[state.selectedNodeIds[0]]:null;const content={src:a.url||`/media/${a.id}/${encodeURIComponent(a.filename||a.original_filename||'asset')}`,asset_id:a.id,alt:a.alt_text||''};if(selected?.type==='image'){dispatch({type:'UPDATE_NODE_CONTENT',payload:{nodeId:selected.id,content}});setMessage('Frame image replaced');return}dispatch({type:'INSERT_NODE',payload:{node:{type:'image',content,style:{css:{width:'320px',height:'220px',objectFit:'cover'},tokens:{}},metadata:{displayName:a.original_filename||a.filename||'Image frame',kind:'image-frame'}}}})};
 const visible=items.filter(a=>String(a.mime_type||'').startsWith('image/')&&String(a.original_filename||a.filename||'').toLowerCase().includes(search.toLowerCase()));
 return <div className="studio-panel assets-panel reference-panel"><div className="reference-search compact"><b>⌕</b><input aria-label="Search images" placeholder="Search images" value={search} onChange={e=>setSearch(e.target.value)}/></div><label className={`asset-upload-button ${busy?'busy':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files)}}><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files)}/><b>{busy?'Uploading…':'Upload files'}</b></label>{message&&<p className="panel-message" role="status">{message}</p>}<div className="asset-tabs" role="tablist"><button className="active" role="tab" aria-selected="true">Images</button></div><div className="asset-grid">{visible.map(a=><button key={a.id} onClick={()=>insert(a)} draggable onDragStart={e=>{e.dataTransfer.setData('application/x-zylora-asset',JSON.stringify(a));e.dataTransfer.effectAllowed='copy'}}><span className="asset-thumb"><img src={a.url||`/media/${a.id}/${encodeURIComponent(a.filename||a.original_filename||'asset')}`} alt=""/></span><small>{a.original_filename||a.filename}</small></button>)}</div>{!items.length&&<div className="empty-state"><b>Your uploads appear here</b><p>Upload an image, then click it or drag it onto a frame.</p></div>}</div>;
}
