import React from 'react';
import {useStudio} from '../store';

const fonts=['Inter','Arial','Georgia','Helvetica Neue','system-ui','Space Grotesk'];
const hover=['none','lift','scale','shadow','underline'];
const entrance=['none','fade','rise','slide','scale'];
const scroll=['none','fade','reveal','rise','slide','scale'];
const styleText=`.context-toolbar{display:flex;align-items:center;gap:6px;min-height:34px;max-width:min(820px,58vw);overflow:auto;white-space:nowrap}.context-toolbar button,.context-toolbar select,.context-toolbar input{height:30px;border:1px solid #d8dce3;border-radius:7px;background:#fff;color:#17191d;padding:0 8px;font-size:11px}.context-toolbar button:hover,.context-toolbar button.active{background:#f1f3f5;border-color:#15171a}.context-toolbar input[type=color]{width:32px;padding:2px}.context-toolbar input[type=number]{width:58px}.context-toolbar select{max-width:148px}.toolbar-selection-label{font-size:11px;color:#59606b;max-width:130px;overflow:hidden;text-overflow:ellipsis;font-weight:700}.toolbar-divider{height:18px;width:1px;background:#dfe2e7}.studio-resize-handle{box-sizing:border-box;border-radius:4px;touch-action:none}.studio-floating-actions{position:absolute;left:50%;top:-24px;transform:translateX(-50%);height:20px;padding:0 8px;border-radius:6px;background:#111;color:#fff;font:700 11px/20px system-ui;z-index:1002;pointer-events:none}.studio-canvas [data-studio-id]{touch-action:pan-y}.studio-canvas [data-studio-id][data-studio-selected=true]{touch-action:none}.studio-canvas img{max-width:100%}`;

export function ContextToolbar({onFit,onPreview}:{onFit:()=>void;onPreview:()=>void}){
 const {state,dispatch}=useStudio(); const page=state.document?.pages[state.currentPageId]; const node=state.selectedNodeIds.length===1?page?.nodes[state.selectedNodeIds[0]]:null;
 const update=(style:Record<string,string>)=>{if(node)dispatch({type:'UPDATE_NODE_STYLE',payload:{nodeId:node.id,style}})};
 const setInteraction=(kind:'hover'|'animation'|'scroll',effect:string)=>{if(!node)return;const existing=(node.interactions||[]).filter(x=>x.trigger!==kind);dispatch({type:'UPDATE_NODE_INTERACTIONS',payload:{nodeId:node.id,interactions:effect==='none'?existing:[...existing,{trigger:kind,effect}]}})};
 const link=()=>{if(!node)return;const href=window.prompt('Link to a page, website, email, phone or section',node.content.href||'');if(href!==null)dispatch({type:'UPDATE_NODE_CONTENT',payload:{nodeId:node.id,content:{href:href||undefined}}})};
 const cycleCrop=()=>{if(!node)return;dispatch({type:'SET_CROP_MODE',payload:node.id})};
 if(!node)return <><style>{styleText}</style><div className="context-toolbar global-toolbar"><button aria-label="Undo" disabled={state.historyIndex<=0} onClick={()=>dispatch({type:'UNDO'})}>↶</button><button aria-label="Redo" disabled={state.historyIndex>=state.history.length-1} onClick={()=>dispatch({type:'REDO'})}>↷</button><span className="toolbar-divider"/><button onClick={onFit}>Fit</button><button onClick={onPreview}>Preview</button></div></>;
 const textLike=['heading','paragraph','text','button','link'].includes(node.type), image=node.type==='image', card=node.type==='container'||node.metadata?.kind==='card';
 return <><style>{styleText}</style><div className="context-toolbar selection-toolbar" onPointerDown={e=>e.stopPropagation()}><span className="toolbar-selection-label">{node.metadata?.displayName|| (image?'Image frame':card?'Card':textLike?'Text':'Selection')}</span>
  {textLike&&<><select aria-label="Font family" value={node.style.css.fontFamily||'Inter'} onChange={e=>update({fontFamily:e.target.value})}>{fonts.map(font=><option key={font}>{font}</option>)}</select><input aria-label="Font size" type="number" min="8" max="220" value={parseInt(node.style.css.fontSize||'16')||16} onChange={e=>update({fontSize:`${e.target.value}px`})}/><button aria-label="Bold" className={node.style.css.fontWeight==='700'?'active':''} onClick={()=>update({fontWeight:node.style.css.fontWeight==='700'?'400':'700'})}>B</button><button aria-label="Italic" className={node.style.css.fontStyle==='italic'?'active':''} onClick={()=>update({fontStyle:node.style.css.fontStyle==='italic'?'normal':'italic'})}>I</button><input aria-label="Text color" type="color" value={/^#[0-9a-f]{6}$/i.test(node.style.css.color||'')?node.style.css.color:'#111111'} onChange={e=>update({color:e.target.value})}/><select aria-label="Text alignment" value={node.style.css.textAlign||'left'} onChange={e=>update({textAlign:e.target.value})}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></>}
  {image&&<><button onClick={()=>document.querySelector<HTMLInputElement>('.assets-panel input[type=file]')?.click()}>Replace</button><button aria-label="Crop" onClick={cycleCrop}>{state.cropNodeId===node.id?'Crop active':'Crop'}</button><select aria-label="Image fit" value={node.style.css.objectFit||'cover'} onChange={e=>update({objectFit:e.target.value})}><option value="cover">Fill</option><option value="contain">Fit</option><option value="fill">Stretch</option></select><button onClick={()=>update({borderRadius:node.style.css.borderRadius?'0px':'16px'})}>Corners</button></>}
  {card&&<><input aria-label="Card background" type="color" value={/^#[0-9a-f]{6}$/i.test(node.style.css.background||'')?node.style.css.background:'#ffffff'} onChange={e=>update({background:e.target.value})}/><button onClick={()=>update({borderRadius:node.style.css.borderRadius?'0px':'16px'})}>Corners</button><button onClick={()=>update({boxShadow:node.style.css.boxShadow?'none':'0 10px 30px rgba(16,24,40,.12)'})}>Shadow</button></>}
  {(textLike||image||card||node.type==='shape')&&<button onClick={link}>Link</button>}
  <select aria-label="Hover effect" value={(node.interactions||[]).find(x=>x.trigger==='hover')?.effect||'none'} onChange={e=>setInteraction('hover',e.target.value)}>{hover.map(x=><option key={x} value={x}>Hover: {x}</option>)}</select><select aria-label="Animation" value={(node.interactions||[]).find(x=>x.trigger==='animation')?.effect||'none'} onChange={e=>setInteraction('animation',e.target.value)}>{entrance.map(x=><option key={x} value={x}>Animate: {x}</option>)}</select><select aria-label="Scroll effect" value={(node.interactions||[]).find(x=>x.trigger==='scroll')?.effect||'none'} onChange={e=>setInteraction('scroll',e.target.value)}>{scroll.map(x=><option key={x} value={x}>On scroll: {x}</option>)}</select><button aria-label="Duplicate" onClick={()=>dispatch({type:'DUPLICATE_NODE',payload:{nodeId:node.id}})}>⧉</button><button aria-label="Delete" onClick={()=>dispatch({type:'DELETE_NODE',payload:{nodeId:node.id}})}>⌫</button>
 </div></>;
}
