import React from 'react';import {Breakpoint,NodeAction,NodeActionType,NodeGeometry,resolveNodeGeometry,useStudio} from '../store';
type Field=[string,string,string?,string[]?];
const sections:Array<[string,Field[]]>=[
 ['Layout',[['Display','display','select',['block','flex','grid','inline-block','none']],['Width','width'],['Min width','minWidth'],['Max width','maxWidth'],['Height','height'],['Min height','minHeight'],['Max height','maxHeight'],['Position','position','select',['relative','absolute','fixed','sticky']],['X / left','left'],['Y / top','top'],['Overflow','overflow','select',['visible','hidden','auto','scroll']],['Direction','flexDirection','select',['row','column','row-reverse','column-reverse']],['Justify','justifyContent'],['Align','alignItems'],['Wrap','flexWrap'],['Columns','gridTemplateColumns'],['Rows','gridTemplateRows'],['Gap','gap']]],
 ['Spacing',[['Margin top','marginTop'],['Margin right','marginRight'],['Margin bottom','marginBottom'],['Margin left','marginLeft'],['Padding top','paddingTop'],['Padding right','paddingRight'],['Padding bottom','paddingBottom'],['Padding left','paddingLeft']]],
 ['Typography',[['Font family','fontFamily'],['Size','fontSize'],['Weight','fontWeight'],['Line height','lineHeight'],['Letter spacing','letterSpacing'],['Align','textAlign','select',['left','center','right','justify']],['Transform','textTransform','select',['none','uppercase','lowercase','capitalize']],['Decoration','textDecoration'],['Color','color','color']]],
 ['Fill',[['Background','backgroundColor','color'],['Opacity','opacity']]],
 ['Border',[['Width','borderWidth'],['Style','borderStyle','select',['none','solid','dashed','dotted']],['Color','borderColor','color'],['Radius','borderRadius'],['Top left','borderTopLeftRadius'],['Top right','borderTopRightRadius'],['Bottom right','borderBottomRightRadius'],['Bottom left','borderBottomLeftRadius']]],
 ['Effects',[['Shadow','boxShadow'],['Transform','transform']]]
];
export function Inspector(){const {state,dispatch}=useStudio();const [open,setOpen]=React.useState<Record<string,boolean>>({Layout:true,Spacing:true,Typography:true,Content:true,CMS:true});const page=state.document?.pages[state.currentPageId],nodes=state.selectedNodeIds.map(id=>page?.nodes[id]).filter(Boolean) as any[];
 if(!nodes.length)return <div className="empty-state inspector-empty"><b>Select something on the canvas</b><p>Layout, content, responsive styles, CMS bindings, and accessibility settings will appear here.</p></div>;
 const node=nodes[0],multi=nodes.length>1,bp=state.currentBreakpoint;
 const pageOptions=Object.values(state.document?.pages||{});
 const legacyAction:NodeAction=node.content.action||{type:node.content.href?'external':'none',url:node.content.href||''};
 const setAction=(type:NodeActionType,value?:string)=>{const action:NodeAction=type==='page'?{type,pageId:value}:type==='section'?{type,sectionId:value}:type==='external'?{type,url:value}:type==='email'||type==='phone'?{type,value}:type==='booking'||type==='form'?{type,value:value||undefined}:{type:'none'};const legacyHref=type==='external'?value:type==='email'?(value?`mailto:${value}`:undefined):type==='phone'?(value?`tel:${value}`:undefined):undefined;dispatch({type:'UPDATE_NODE_CONTENT',payload:{nodeId:node.id,content:{action,href:legacyHref}}})};
 const geometry=resolveNodeGeometry(node,bp);
 const value=(prop:string)=>{const base=node.style.css[prop]||'',tablet=node.responsiveOverrides.tablet?.style?.css[prop],own=node.responsiveOverrides[bp]?.style?.css[prop];return {value:bp==='desktop'?base:(own!==undefined?own:(bp==='mobile'&&tablet!==undefined?tablet:base)),override:bp!=='desktop'&&own!==undefined}};
 const update=(prop:string,v:string)=>dispatch({type:multi?'UPDATE_SELECTED_STYLE':'UPDATE_NODE_STYLE',...(multi?{payload:{[prop]:v}}:{payload:{nodeId:node.id,style:{[prop]:v}}})} as any);
 const updateGeometry=(property:keyof NodeGeometry,value:string)=>{const cssKey:Record<string,string>={x:'left',y:'top',width:'width',height:'height',rotation:'rotate'};const css=cssKey[String(property)];if(!css)return;const numeric=Number(value);if(!Number.isFinite(numeric))return;const items=(multi?nodes:[node]).map(item=>({nodeId:item.id,geometry:{[css]:`${numeric}${property==='rotation'?'deg':'px'}`}}));dispatch({type:'UPDATE_SELECTED_GEOMETRIES',payload:{geometries:items}})};
 const geometryField=(label:string,property:keyof NodeGeometry)=>{const value=geometry[property];const overridden=bp!=='desktop'&&node.responsiveOverrides[bp]?.geometry?.[property]!==undefined;return <label className={`inspector-field geometry-field ${overridden?'overridden':''}`} key={String(property)}><span>{label}{overridden&&<i title="Overridden at this breakpoint">●</i>}</span><span className="field-control"><input aria-label={label} type="number" step={property==='rotation'?1:1} value={Number(value)} onChange={event=>updateGeometry(property,event.target.value)}/>{overridden&&<button title="Reset geometry override" onClick={()=>dispatch({type:'RESET_NODE_GEOMETRY',payload:{nodeId:node.id,property,breakpoint:bp}})}>↺</button>}</span></label>};
 const field=([label,prop,kind='text',choices]:Field)=>{const current=value(prop);return <label className={`inspector-field ${current.override?'overridden':''}`} key={prop}><span>{label}{current.override&&<i title="Overridden at this breakpoint">●</i>}</span><span className="field-control">{kind==='select'?<select value={current.value} onChange={e=>update(prop,e.target.value)}><option value="">Auto</option>{choices?.map(x=><option key={x}>{x}</option>)}</select>:kind==='color'?<><input type="color" value={/^#[0-9a-f]{6}$/i.test(current.value)?current.value:'#000000'} onChange={e=>update(prop,e.target.value)}/><input value={current.value} placeholder="Inherited" onChange={e=>update(prop,e.target.value)}/></>:<input value={current.value} placeholder="Inherited" onChange={e=>update(prop,e.target.value)}/>} {current.override&&<button title="Reset override" onClick={()=>dispatch({type:'RESET_NODE_STYLE',payload:{nodeId:node.id,prop,breakpoint:bp}})}>↺</button>}</span></label>};
 const section=(name:string,body:React.ReactNode)=><section className="inspector-section" key={name}><button className="section-heading" onClick={()=>setOpen(o=>({...o,[name]:o[name]===false}))}><span>{name}</span><span>{open[name]===false?'›':'⌄'}</span></button>{open[name]!==false&&<div className="section-body">{body}</div>}</section>;
 return <div className="inspector"><div className="inspector-selection"><span className="node-glyph">{multi?'◫':'◇'}</span><span><b>{multi?`${nodes.length} elements`:node.metadata?.displayName||node.type}</b><small>{multi?'Batch changes apply to every selection':node.type}</small></span>{!multi&&<button title={node.metadata?.locked?'Unlock':'Lock'} onClick={()=>dispatch({type:'TOGGLE_NODE_LOCK',payload:{nodeId:node.id}})}>{node.metadata?.locked?'⌾':'○'}</button>}</div>
 {section('Transform',<div className="geometry-grid"><div className="geometry-grid-row">{geometryField('X', 'x')}{geometryField('Y', 'y')}</div><div className="geometry-grid-row">{geometryField('Width','width')}{geometryField('Height','height')}</div>{geometryField('Rotation','rotation')}<p className="panel-hint">Values are in page coordinates. A blue dot means this breakpoint overrides the inherited value.</p></div>)}
 {multi&&section('Arrange',<div className="button-grid"><button onClick={()=>update('alignSelf','flex-start')}>Left</button><button onClick={()=>update('alignSelf','center')}>Center</button><button onClick={()=>update('alignSelf','flex-end')}>Right</button><button onClick={()=>update('justifySelf','start')}>Top</button><button onClick={()=>update('justifySelf','center')}>Middle</button><button onClick={()=>update('justifySelf','end')}>Bottom</button></div>)}
 {!multi&&['heading','paragraph','text','button','link'].includes(node.type)&&section('Content',<><label className="inspector-field vertical"><span>Text</span><textarea value={node.content.text||''} onChange={e=>dispatch({type:'UPDATE_NODE_CONTENT',payload:{nodeId:node.id,content:{text:e.target.value,html:undefined}}})}/></label>{['button','link'].includes(node.type)&&<><label className="inspector-field"><span>Action</span><select aria-label="Link action" value={legacyAction.type} onChange={e=>setAction(e.target.value as NodeActionType,legacyAction.type==='page'?legacyAction.pageId:legacyAction.type==='section'?legacyAction.sectionId:legacyAction.type==='external'?legacyAction.url:legacyAction.value)}><option value="none">No action</option><option value="page">Internal page</option><option value="section">Section anchor</option><option value="external">External URL</option><option value="email">Email</option><option value="phone">Phone</option><option value="booking">Booking</option><option value="form">Form</option></select></label>{legacyAction.type==='page'&&<label className="inspector-field"><span>Page</span><select aria-label="Internal page" value={legacyAction.pageId||''} onChange={e=>setAction('page',e.target.value)}><option value="">Choose a page</option>{pageOptions.map(item=><option key={item.id} value={item.id}>{item.name} · /{item.slug==='home'?'':item.slug}</option>)}</select></label>}{legacyAction.type==='section'&&<label className="inspector-field"><span>Section ID</span><input value={legacyAction.sectionId||''} onChange={e=>setAction('section',e.target.value)} placeholder="section-node-id"/></label>}{(['external','email','phone'].includes(legacyAction.type))&&<label className="inspector-field"><span>{legacyAction.type==='external'?'URL':legacyAction.type==='email'?'Email address':'Phone number'}</span><input type={legacyAction.type==='email'?'email':legacyAction.type==='phone'?'tel':'url'} value={legacyAction.type==='external'?legacyAction.url||'':legacyAction.value||''} onChange={e=>setAction(legacyAction.type,e.target.value)} placeholder={legacyAction.type==='external'?'https://example.com':legacyAction.type==='email'?'hello@example.com':'+1 555 123 4567'}/></label>}<p className="panel-hint">Internal page links use the page ID, so changing a slug will not break them.</p></>}</>)}
 {!multi&&node.type==='image'&&section('Image',<><label className="inspector-field"><span>Source</span><input value={node.content.src||''} onChange={e=>dispatch({type:'UPDATE_NODE_CONTENT',payload:{nodeId:node.id,content:{src:e.target.value}}})}/></label><label className="inspector-field"><span>Alt text</span><input value={node.content.alt||''} onChange={e=>dispatch({type:'UPDATE_NODE_CONTENT',payload:{nodeId:node.id,content:{alt:e.target.value}}})}/></label>{field(['Fit','objectFit','select',['cover','contain','fill','none']])}{field(['Focal point','objectPosition'])}</>)}
 {sections.map(([name,fields])=>section(name,fields.map(field)))}
 {!multi&&section('Responsive',<><div className="responsive-summary">{(['desktop','tablet','mobile'] as Breakpoint[]).map(x=><button className={bp===x?'active':''} onClick={()=>dispatch({type:'SET_BREAKPOINT',payload:x})} key={x}>{x[0].toUpperCase()}</button>)}</div><button className="wide-button" onClick={()=>dispatch({type:'TOGGLE_NODE_VISIBILITY',payload:{nodeId:node.id,breakpoint:bp}})}>{node.visibility==='hidden'?'Show':'Hide'} on {bp}</button><p className="panel-hint">Blue dots identify local overrides. Reset any value to inherit it again.</p></>)}
 {!multi&&section('CMS',<><div className={`binding-status ${Object.keys(node.bindings||{}).length?'bound':''}`}><span>◉</span><span><b>{Object.keys(node.bindings||{}).length?'Connected to CMS':'Not connected'}</b><small>{Object.keys(node.bindings||{}).length?'Bindings use stable field IDs':'Choose CMS in the left rail to bind data'}</small></span></div></>)}
 {!multi&&section('Accessibility',<><label className="inspector-field"><span>ARIA label</span><input value={node.accessibility?.ariaLabel||''} onChange={e=>dispatch({type:'UPDATE_NODE_ACCESSIBILITY',payload:{nodeId:node.id,accessibility:{ariaLabel:e.target.value}}})}/></label><label className="inspector-field"><span>Element ID</span><input readOnly value={node.id}/></label></>)}
 </div>}
