import React from 'react';

type UserTemplate={id:string;name:string;description:string;updated_at:string;compatible?:boolean;schema_version?:number|null};

export function UserTemplatesPanel({onClose}:{onClose:()=>void}){
  const [items,setItems]=React.useState<UserTemplate[]>([]);
  const [query,setQuery]=React.useState('');
  const [status,setStatus]=React.useState('Loading your templates…');
  const csrf=(window as any).ZYLORA_STUDIO_CONTEXT?.csrfToken;
  React.useEffect(()=>{fetch('/api/user-templates').then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data?.detail||'Could not load templates');setItems(data.items||[]);setStatus(data.items?.length?'':'No saved templates yet.')}).catch(error=>setStatus(String(error.message||error)))},[]);
  const create=async(template:UserTemplate)=>{if(template.compatible===false){setStatus('This template was created with an older Studio schema and cannot be applied safely.');return}const name=window.prompt('Name the new website',`${template.name} copy`);if(!name)return;setStatus('Creating website…');const response=await fetch(`/api/user-templates/${template.id}/create`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({name})});const data=await response.json();if(response.ok)location.href=data.studio_url;else setStatus(data?.detail?.message||data?.detail||'Could not create website')};
  const filtered=items.filter(item=>[item.name,item.description].some(value=>String(value||'').toLowerCase().includes(query.trim().toLowerCase())));
  return <div className="user-template-overlay" role="dialog" aria-modal="true" aria-label="Templates"><div className="user-template-dialog"><header><div><b>Templates</b><span>Current-schema, private reusable copies of your designs.</span></div><button onClick={onClose} aria-label="Close templates">×</button></header><label className="template-search">Search templates<input aria-label="Search templates" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search templates"/></label><div className="user-template-list">{filtered.map(item=><article key={item.id}><div className="template-miniature" aria-hidden="true"><i/><i/><i/></div><div><b>{item.name}</b><p>{item.description||'Reusable website design'}</p><small>{item.compatible===false?'Older schema · unavailable':`Studio schema ${item.schema_version||5} · ${new Date(item.updated_at).toLocaleDateString()}`}</small></div><button disabled={item.compatible===false} onClick={()=>create(item)}>{item.compatible===false?'Unavailable':'Use'}</button></article>)}</div>{!filtered.length&&!status&&<p className="template-status">No templates match that search.</p>}{status&&<p className="template-status" role="status">{status}</p>}</div></div>;
}
